import test from 'node:test';import assert from 'node:assert/strict';
import {seedOrg,seedDemo,get,addIdentity,consume,remaining,status,descendants,full} from '../lib/demo-model.mjs';
const wallet='0x'+'a'.repeat(40);
function scenario(){let nodes=seedOrg();let user=addIdentity(nodes,get(nodes,'dev'),{name:'derek',wallet,limits:{codex:20,openai:5,github:null,linear:null},period:'month'});let agent=addIdentity(nodes,user,{name:'codex',wallet,limits:{codex:5,openai:2},period:'session',until:Date.now()+480000});let image=addIdentity(nodes,agent,{name:'image',wallet,limits:{openai:1},period:'session',until:Date.now()+60000});return {nodes,user,agent,image}}
test('six-level organization and canonical member name',()=>{const {nodes,user,image}=scenario();assert.equal(nodes.filter(n=>n.type==='department').length,3);assert.equal(nodes.filter(n=>n.type==='team').length,6);assert.equal(full(nodes,user),'derek.dev.eng.acme.eth');assert.equal(full(nodes,image),'image.codex.derek.dev.eng.acme.eth')});
test('parent constraints reject unauthorized APIs, overages, bad wallets',()=>{const nodes=seedOrg(),p=get(nodes,'dev');const v={name:'derek',wallet,limits:{stripe:null},period:'month'};assert.throws(()=>addIdentity(nodes,p,v),/does not allow/);assert.throws(()=>addIdentity(nodes,p,{...v,limits:{codex:1001}}),/within/);assert.throws(()=>addIdentity(nodes,p,{...v,limits:{codex:20},wallet:'0x123'}),/complete/)});
test('one request succeeds and second fails without incrementing any counter',()=>{const {nodes,user,agent,image}=scenario();consume(nodes,image,'openai',1);for(const n of [get(nodes,'acme'),get(nodes,'eng'),get(nodes,'dev'),user,agent,image])assert.equal(n.usage.openai,1);assert.throws(()=>consume(nodes,image,'openai',1),/exhausted/);assert.equal(agent.usage.openai,1)});
test('parent dollar cap constrains concurrent child usage',()=>{const {nodes,user,agent}=scenario();user.limits.codex=.3;consume(nodes,agent,'codex',.25);assert.ok(remaining(nodes,agent,'codex')<.051);assert.throws(()=>consume(nodes,agent,'codex',.25),/exhausted/)});
test('revocation and expiry cascade; reused names start with no spend',()=>{const {nodes,user,agent,image}=scenario();consume(nodes,image,'openai',1);user.removed=true;assert.equal(status(nodes,image),'Revoked');assert.throws(()=>consume(nodes,image,'openai',1),/revoked/);for(const n of descendants(nodes,user.id))n.removed=true;const fresh=addIdentity(nodes,get(nodes,'dev'),{name:'derek',wallet,limits:{codex:20},period:'month'});assert.deepEqual(fresh.usage,{});user.removed=false;agent.removed=false;agent.until=Date.now()-1;assert.equal(status(nodes,agent),'Expired')});

test('populated demo has all six layers and reconciled usage',()=>{const nodes=seedDemo();assert.deepEqual([...new Set(nodes.map(n=>n.type))],['company','department','team','member','agent','subagent']);assert.equal(nodes.filter(n=>['agent','subagent'].includes(n.type)).length,13);assert.equal(get(nodes,'acme').usage.codex,4.5);assert.equal(get(nodes,'acme').usage.openai,10);});

test('every team contains users, agents and subagents',()=>{const nodes=seedDemo();for(const team of nodes.filter(n=>n.type==='team')){const branch=descendants(nodes,team.id);for(const type of ['member','agent','subagent'])assert.ok(branch.some(n=>n.type===type),team.name+' missing '+type)}});

test('retired image provider is absent from every demo permission',()=>{for(const n of seedDemo())assert.equal(Object.hasOwn(n.limits,'images'),false)});
