// Generated by scripts/gen-ens-abis.mjs from ensdomains/contracts-v2@71a3b73. Do not edit.

export const ensErrorsAbi = [
  {
    "inputs": [],
    "name": "AccountAccessUnauthorized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AccountAlreadyInitialized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AccountNotInitialized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "ActionNotAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "AddressEmptyCode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CallerNotAdmin",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CallerNotIntentExecutor",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CallerNotOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "oldExpiry",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "newExpiry",
        "type": "uint64"
      }
    ],
    "name": "CannotReduceExpiry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CanNotRemoveLastValidator",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "expiry",
        "type": "uint64"
      }
    ],
    "name": "CannotSetPastExpiry",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "commitment",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "validFrom",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "blockTimestamp",
        "type": "uint64"
      }
    ],
    "name": "CommitmentTooNew",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "commitment",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "validTo",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "blockTimestamp",
        "type": "uint64"
      }
    ],
    "name": "CommitmentTooOld",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ComposableExecutionFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "enum ConstraintType",
        "name": "constraintType",
        "type": "uint8"
      }
    ],
    "name": "ConstraintNotMet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DefaultValidatorAlreadyInstalled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DelegateCallNotAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "dns",
        "type": "bytes"
      }
    ],
    "name": "DNSDecodingFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "ens",
        "type": "string"
      }
    ],
    "name": "DNSEncodingFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "duration",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "minDuration",
        "type": "uint64"
      }
    ],
    "name": "DurationTooShort",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "EACCannotGrantRoles",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "EACCannotRevokeRoles",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EACInvalidAccount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      }
    ],
    "name": "EACInvalidRoleBitmap",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "role",
        "type": "uint256"
      }
    ],
    "name": "EACMaxAssignees",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "role",
        "type": "uint256"
      }
    ],
    "name": "EACMinAssignees",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EACRootResourceNotAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "resource",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roleBitmap",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "EACUnauthorizedAccountRoles",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ECDSAInvalidSignature",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "ECDSAInvalidSignatureLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "s",
        "type": "bytes32"
      }
    ],
    "name": "ECDSAInvalidSignatureS",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmergencyTimeLockNotExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmergencyUninstallSigError",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EnableModeSigError",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EntryPointCanNotBeZero",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "balance",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "needed",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ERC1155InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "approver",
        "type": "address"
      }
    ],
    "name": "ERC1155InvalidApprover",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idsLength",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "valuesLength",
        "type": "uint256"
      }
    ],
    "name": "ERC1155InvalidArrayLength",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      }
    ],
    "name": "ERC1155InvalidOperator",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      }
    ],
    "name": "ERC1155InvalidReceiver",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "ERC1155InvalidSender",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "ERC1155MissingApprovalForAll",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "ERC1967InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC1967NonPayable",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "allowance",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "needed",
        "type": "uint256"
      }
    ],
    "name": "ERC20InsufficientAllowance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "balance",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "needed",
        "type": "uint256"
      }
    ],
    "name": "ERC20InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "approver",
        "type": "address"
      }
    ],
    "name": "ERC20InvalidApprover",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      }
    ],
    "name": "ERC20InvalidReceiver",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "ERC20InvalidSender",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      }
    ],
    "name": "ERC20InvalidSpender",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "ERC2612ExpiredSignature",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "ERC2612InvalidSigner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ERC7702AccountCannotBeUpgradedThisWay",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExecutionFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FailedCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "FallbackAlreadyInstalledForSelector",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FallbackCallTypeInvalid",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FallbackHandlerUninstallFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "FallbackNotInstalledForSelector",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "FallbackSelectorForbidden",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "FrozenTokenApproval",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GasRefundNotAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "hca",
        "type": "address"
      }
    ],
    "name": "HCADeploymentNotTrusted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "HCAImplementationCannotBeZero",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "hcaImplementation",
        "type": "address"
      }
    ],
    "name": "HCAImplementationNotApproved",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "hcaOwner",
        "type": "address"
      }
    ],
    "name": "HCAOwnerMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "hca",
        "type": "address"
      }
    ],
    "name": "HCAOwnerUnavailable",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "currentHook",
        "type": "address"
      }
    ],
    "name": "HookAlreadyInstalled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "HookPostCheckFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "status",
        "type": "uint16"
      },
      {
        "internalType": "string",
        "name": "message",
        "type": "string"
      }
    ],
    "name": "HttpError",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ImplementationIsNotAContract",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InnerCallFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InputLengthMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "currentNonce",
        "type": "uint256"
      }
    ],
    "name": "InvalidAccountNonce",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidBaseRates",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidBatchGatewayResponse",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidConstraintType",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "contentType",
        "type": "uint256"
      }
    ],
    "name": "InvalidContentType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidData",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "expected",
        "type": "uint256"
      }
    ],
    "name": "InvalidDataLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDiscount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "addressBytes",
        "type": "bytes"
      }
    ],
    "name": "InvalidEVMAddress",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "InvalidHexData",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidImplementationAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitData",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInitialization",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidInput",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "module",
        "type": "address"
      }
    ],
    "name": "InvalidModule",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "moduleTypeId",
        "type": "uint256"
      }
    ],
    "name": "InvalidModuleTypeId",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidNonce",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidOperationEncoding",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidOutputParamFetcherType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidParameterEncoding",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPREP",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRatio",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRecord",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSessionData",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidShortString",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSigner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTXT",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "LabelAlreadyRegistered",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "LabelAlreadyReserved",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "LabelExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LabelIsEmpty",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "LabelIsTooLong",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "entry",
        "type": "address"
      }
    ],
    "name": "LinkedList_InvalidEntry",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LinkedList_InvalidPage",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MaxCommitmentAgeTooLow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MismatchModuleTypeId",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "MissingFallbackHandler",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ModuleAddressCanNotBeZero",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "moduleTypeId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "module",
        "type": "address"
      }
    ],
    "name": "ModuleAlreadyInstalled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "moduleTypeId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "module",
        "type": "address"
      }
    ],
    "name": "ModuleNotInstalled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "NameDataMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "NameIsLocked",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "NameNotAvailable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NameNotClearable",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "NameNotLocked",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "NameNotRenewable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NameRequiresMigration",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NameRequiresPreimage",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NexusInitializationFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoModuleChangeAllowed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoNFTAllowed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "normalizedName",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "result",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "resolver",
        "type": "address"
      }
    ],
    "name": "NormalizationChangedName",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "suffix",
        "type": "bytes"
      }
    ],
    "name": "NoSuffixMatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "nft",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "NotApprovedOperator",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotInitializing",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "NotValid",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoValidatorInstalled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "string[]",
        "name": "urls",
        "type": "string[]"
      },
      {
        "internalType": "bytes",
        "name": "callData",
        "type": "bytes"
      },
      {
        "internalType": "bytes4",
        "name": "callbackFunction",
        "type": "bytes4"
      },
      {
        "internalType": "bytes",
        "name": "extraData",
        "type": "bytes"
      }
    ],
    "name": "OffchainLookup",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "OffsetOutOfBoundsError",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Output_StaticCallFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OwnerCannotBeZero",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OwnerUnavailable",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      }
    ],
    "name": "ParentNotMigrated",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "contract IERC20",
        "name": "paymentToken",
        "type": "address"
      }
    ],
    "name": "PaymentTokenNotSupported",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PolicyRuleFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "currentPreValidationHook",
        "type": "address"
      }
    ],
    "name": "PrevalidationHookAlreadyInstalled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "primary",
        "type": "string"
      }
    ],
    "name": "PrimaryNameNotNormalized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "errorData",
        "type": "bytes"
      }
    ],
    "name": "ResolverError",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      },
      {
        "internalType": "address",
        "name": "resolver",
        "type": "address"
      }
    ],
    "name": "ResolverNotContract",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      }
    ],
    "name": "ResolverNotFound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "primary",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "primaryAddress",
        "type": "bytes"
      }
    ],
    "name": "ReverseAddressMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SameImplementation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StandaloneHCAAlreadyInitialized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "str",
        "type": "string"
      }
    ],
    "name": "StringTooLong",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      }
    ],
    "name": "TransferDisallowed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TransferUnsafeUntilRegistryIsEmancipated",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      }
    ],
    "name": "TransferUnsafeWithMultipleAssignees",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedCallContext",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "UnauthorizedCaller",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "namer",
        "type": "address"
      }
    ],
    "name": "UnauthorizedNamer",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      }
    ],
    "name": "UnauthorizedOperation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "expectedImplementation",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "actualImplementation",
        "type": "address"
      }
    ],
    "name": "UnexpectedHCAImplementation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "expectedOwner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "actualOwner",
        "type": "address"
      }
    ],
    "name": "UnexpectedHCAOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "commitment",
        "type": "bytes32"
      }
    ],
    "name": "UnexpiredCommitmentExists",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "name",
        "type": "bytes"
      }
    ],
    "name": "UnreachableName",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "name": "UnsafeBatchGatewayResponse",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "CallType",
        "name": "callType",
        "type": "bytes1"
      }
    ],
    "name": "UnsupportedCallType",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "ExecType",
        "name": "execType",
        "type": "bytes1"
      }
    ],
    "name": "UnsupportedExecType",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "moduleTypeId",
        "type": "uint256"
      }
    ],
    "name": "UnsupportedModuleType",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes4",
        "name": "selector",
        "type": "bytes4"
      }
    ],
    "name": "UnsupportedResolverProfile",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UpgradeFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      }
    ],
    "name": "UpgradeTargetNotApproved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UUPSUnauthorizedCallContext",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "slot",
        "type": "bytes32"
      }
    ],
    "name": "UUPSUnsupportedProxiableUUID",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "module",
        "type": "address"
      }
    ],
    "name": "ValidatorNotInstalled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VerifiableFactoryCannotBeZero",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "proxy",
        "type": "address"
      }
    ],
    "name": "VerificationFailed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "WrappedOwnerMismatch",
    "type": "error"
  }
] as const;
