import { providerMarks } from "./provider-marks.js";
import { catalog, seedOrg, seedDemo, get as findNode, chain, full as fullName, descendants as children, status, used, allowed, remaining, validate, addIdentity, consume } from "./demo-model.mjs";
export function mountWorkspace(root) {
const iconPaths={"relay": "<circle cx=\"7\" cy=\"7\" r=\"3\"/><circle cx=\"25\" cy=\"25\" r=\"3\"/><path d=\"M10 7h9a6 6 0 0 1 0 12h-6a6 6 0 0 0 0 12M22 25H13M7 10v15h5\"/>", "company": "<path d=\"M7 28V5h18v23M3 28h26M13 28v-7h6v7M11 10h2m6 0h2m-10 5h2m6 0h2\"/>", "department": "<rect x=\"3\" y=\"11\" width=\"26\" height=\"17\" rx=\"3\"/><path d=\"M11 11V6h10v5M3 18c8 4 18 4 26 0M14 18h4v5h-4z\"/>", "member": "<circle cx=\"16\" cy=\"11\" r=\"6\"/><path d=\"M5 29v-3a11 11 0 0 1 22 0v3M11 7c2 3 7 4 11 3M12 23l4 4 4-4\"/>", "agent": "<rect x=\"5\" y=\"9\" width=\"22\" height=\"18\" rx=\"5\"/><path d=\"M16 9V4M2 16v5m28-5v5M12 22h8\"/><circle cx=\"16\" cy=\"3\" r=\"1\"/><circle cx=\"11\" cy=\"16\" r=\"1.4\" fill=\"currentColor\"/><circle cx=\"21\" cy=\"16\" r=\"1.4\" fill=\"currentColor\"/>", "subagent": "<rect x=\"8\" y=\"12\" width=\"21\" height=\"17\" rx=\"4\"/><path d=\"M18 12V8M3 4v14h5M14 24h9\"/><circle cx=\"14\" cy=\"18\" r=\"1\" fill=\"currentColor\"/><circle cx=\"23\" cy=\"18\" r=\"1\" fill=\"currentColor\"/>", "tree": "<rect x=\"12\" y=\"3\" width=\"8\" height=\"7\" rx=\"1\"/><rect x=\"2\" y=\"23\" width=\"8\" height=\"7\" rx=\"1\"/><rect x=\"22\" y=\"23\" width=\"8\" height=\"7\" rx=\"1\"/><path d=\"M16 10v7H6v6m10-6h10v6\"/>", "providers": "<rect x=\"3\" y=\"3\" width=\"10\" height=\"10\" rx=\"2\"/><rect x=\"19\" y=\"3\" width=\"10\" height=\"10\" rx=\"2\"/><rect x=\"3\" y=\"19\" width=\"10\" height=\"10\" rx=\"2\"/><rect x=\"19\" y=\"19\" width=\"10\" height=\"10\" rx=\"2\"/>", "activity": "<path d=\"M9 3h17v26H6V6h3zM12 10h9m-9 6h9m-9 6h5M3 10h3M3 17h3M3 24h3\"/>", "clock": "<circle cx=\"16\" cy=\"16\" r=\"12\"/><path d=\"M16 8v9l6 3M16 2V0\"/>", "wallet": "<path d=\"M27 10V6H7a4 4 0 0 0 0 8h22v14H7a4 4 0 0 1-4-4V10M29 17h-9v7h9\"/><circle cx=\"24\" cy=\"20.5\" r=\"1\" fill=\"currentColor\"/>", "chart": "<path d=\"M4 4v24h25M9 21v-6m7 6V9m7 12V4\"/>", "shield": "<path d=\"M16 3L5 7v9c0 7 11 13 11 13s11-6 11-13V7zM10 16l4 4 8-9\"/>", "claude": "<path d=\"M16 3v26M3 16h26M7 7l18 18M7 25L25 7M11 4l10 24M4 11l24 10M4 21l24-10M11 28L21 4\"/>", "codex": "<path d=\"M12 8L4 16l8 8m8-16 8 8-8 8M18 5l-4 22\"/>", "github": "<circle cx=\"9\" cy=\"6\" r=\"3\"/><circle cx=\"9\" cy=\"26\" r=\"3\"/><circle cx=\"25\" cy=\"8\" r=\"3\"/><path d=\"M9 9v14m0-5h8a8 8 0 0 0 8-7\"/>", "railway": "<rect x=\"4\" y=\"4\" width=\"24\" height=\"10\" rx=\"2\"/><rect x=\"4\" y=\"19\" width=\"24\" height=\"10\" rx=\"2\"/><path d=\"M9 9h1m5 0h8M9 24h1m5 0h8M16 14v5\"/>", "search": "<circle cx=\"13\" cy=\"13\" r=\"9\"/><path d=\"M20 20l9 9\"/>", "reset": "<path d=\"M5 11a12 12 0 1 1 1 13M5 3v8h8\"/>", "plus": "<path d=\"M16 5v22M5 16h22\"/>", "minus": "<path d=\"M5 16h22\"/>", "close": "<path d=\"M7 7l18 18M7 25L25 7\"/>", "arrow": "<path d=\"M7 25L25 7M7 7h18v18\"/>", "fit": "<path d=\"M3 12V3h9m8 0h9v9m0 8v9h-9m-8 0H3v-9\"/>", "check": "<path d=\"M5 16l7 7L27 8\"/>", "ens": "<path d=\"M16 2L5 15l11 15 11-15zM5 15l11 5 11-5M16 2v18\"/>"};
function icon(name){const mark=providerMarks[name];if(mark)return `<svg class="ui-icon brand-icon brand-${name}" viewBox="${mark.viewBox}" fill="currentColor" fill-rule="evenodd" stroke="none" aria-hidden="true">${mark.body}</svg>`;return `<svg class="ui-icon" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.providers}</svg>`}
const $=s=>root.querySelector(s), $$=s=>[...root.querySelectorAll(s)];
let nodes=seedDemo(),selected='dev',zoom=1,fitted=true,filter='',branch='all',editing=null;
let events=[{title:'Demo organization prepared',detail:'3 departments · 6 teams · 6 users · 6 agents · 7 subagents · $13.50 mock usage',time:'Initial state'}];
const get=id=>findNode(nodes,id),full=n=>fullName(nodes,n),desc=id=>children(nodes,id),live=n=>status(nodes,n)==='Active';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+n.toFixed(2),labelUnit=(key,value)=>catalog[key].unit==='usd'?money(value):catalog[key].unit==='count'?value+' images':'Allowed';
function log(title,detail){events.unshift({title,detail,time:new Date().toLocaleTimeString()});renderActivity()}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000)}
function visible(){let list=nodes.filter(n=>!n.removed);if(branch!=='all')list=list.filter(n=>n.id==='acme'||chain(nodes,n).some(p=>p.id===branch));return list}
function layout(list){let cursor=120;const set=new Set(list.map(n=>n.id));function visit(n,depth){const kids=list.filter(p=>p.parent===n.id);n.y=20+depth*145;if(!kids.length){n.x=cursor;cursor+=220}else{kids.forEach(p=>visit(p,depth+1));n.x=(kids[0].x+kids.at(-1).x)/2}}visit(get('acme'),0);return {width:Math.max(650,cursor),height:Math.max(880,Math.max(...list.map(n=>n.y))+135)}}

let providerPopup=null,providerTrigger=null;
function providerCircles(n){const keys=allowed(nodes,n),shown=keys.length>3?keys.slice(0,2):keys;return shown.map(k=>`<span class="provider-circle" title="${esc(catalog[k].name)}">${icon(k)}</span>`).join('')+(keys.length>3?`<button class="provider-circle provider-overflow" data-owner="${n.id}" aria-label="Show all ${keys.length} providers for ${esc(n.label)}" aria-expanded="false">…</button>`:'')}
function closeProviderList(){providerPopup?.remove();providerPopup=null;providerTrigger?.setAttribute('aria-expanded','false');providerTrigger=null}
function openProviderList(trigger){if(providerTrigger===trigger){closeProviderList();return}closeProviderList();providerTrigger=trigger;trigger.setAttribute('aria-expanded','true');const n=get(trigger.dataset.owner);providerPopup=document.createElement('section');providerPopup.className='node-provider-popover';providerPopup.setAttribute('aria-label',n.label+' providers');providerPopup.innerHTML=`<strong>${esc(n.label)} · Providers</strong><div>${allowed(nodes,n).map(k=>`<span class="expanded-provider"><i class="provider-circle">${icon(k)}</i>${esc(catalog[k].name)}</span>`).join('')}</div>`;root.appendChild(providerPopup);const r=trigger.getBoundingClientRect(),p=providerPopup.getBoundingClientRect();providerPopup.style.left=Math.max(8,Math.min(r.left,innerWidth-p.width-8))+'px';providerPopup.style.top=Math.max(8,Math.min(r.bottom+8,innerHeight-p.height-8))+'px'}
const dismissProviders=e=>{if(providerPopup&&!providerPopup.contains(e.target)&&!providerTrigger?.contains(e.target))closeProviderList()};
const escapeProviders=e=>{if(e.key==='Escape'){const trigger=providerTrigger;closeProviderList();trigger?.focus()}};
document.addEventListener('click',dismissProviders);document.addEventListener('scroll',closeProviderList,true);document.addEventListener('keydown',escapeProviders);window.addEventListener('resize',closeProviderList);

function render(){closeProviderList();const list=visible(),size=layout(list),path=chain(nodes,get(selected)).map(n=>n.id);$('#graph').style.width=size.width+'px';$('#graph').style.height=size.height+'px';$('#nodes').innerHTML=list.map(n=>`<div role="button" tabindex="0" class="node ${selected===n.id?'selected':''} ${path.includes(n.id)?'path-parent':''} ${live(n)?'':'revoked'} ${filter&&!full(n).includes(filter)?'match-dim':''}" style="left:${n.x}px;top:${n.y}px" data-id="${n.id}" aria-label="${full(n)}, ${n.type}" aria-pressed="${selected===n.id}"><div class="node-top"><span class="node-icon">${icon(n.type==='team'?'department':n.type)}</span><span class="node-name">${esc(n.label)}</span><span class="node-status"></span></div><div class="node-sub">${full(n)}</div><div class="node-foot provider-stack">${providerCircles(n)}</div><i class="node-port"></i></div>` ).join('')+['COMPANY','DEPARTMENT','TEAM','USER','AGENT','SUBAGENT'].map((l,i)=>`<div class="level-label" style="top:${37+i*145}px">0${i+1}<span>${l}</span></div>`).join('');
$('#connections').setAttribute('width',size.width);$('#connections').setAttribute('height',size.height);$('#connections').innerHTML=list.filter(n=>n.parent).map(n=>{let p=get(n.parent),sx=p.x+92.5,sy=p.y+105,ex=n.x+92.5,ey=n.y,m=(sy+ey)/2;return `<path class="${path.includes(n.id)?'onpath':''} ${live(n)?'':'off'}" d="M${sx},${sy} C${sx},${m} ${ex},${m} ${ex},${ey}"/>`}).join('');$$('.node').forEach(b=>{b.onclick=()=>select(b.dataset.id);b.onkeydown=e=>{if(e.target===b&&['Enter',' '].includes(e.key)){e.preventDefault();select(b.dataset.id)}}});$$('.provider-overflow').forEach(b=>b.onclick=e=>{e.stopPropagation();openProviderList(b)});$('#activeCount').textContent=nodes.filter(live).length;$('#navCount').textContent=list.length;$('#subagentSummary').textContent='includes '+nodes.filter(n=>live(n)&&n.type==='subagent').length+' subagents';$('#agentCount').textContent=nodes.filter(n=>live(n)&&['agent','subagent'].includes(n.type)).length;$('#totalUsage').textContent=money(Object.keys(catalog).filter(k=>catalog[k].unit==='usd').reduce((s,k)=>s+used(get('acme'),k),0));renderDetails();renderActivity();if(fitted)fitTree()}
function select(id){selected=id;render()}
function renderDetails(){const n=get(selected),parent=get(n.parent),active=live(n),session=['agent','subagent'].includes(n.type);$('#details').innerHTML=`<div class="detail-topline">${n.type.toUpperCase()} DETAILS <span class="status-pill ${active?'':'revoked'}">${status(nodes,n)}</span></div><div class="detail-icon">${icon(n.type==='team'?'department':n.type)}</div><h2>${esc(n.label)}</h2><div class="full-name">${full(n)}</div><div class="owner-row"><span>Owner wallet</span><b title="${n.wallet}">${n.wallet.slice(0,6)}…${n.wallet.slice(-4)}</b></div><div class="detail-section"><div class="detail-section-title">API permissions <span>${Object.keys(n.limits).length} APIs</span></div>${Object.entries(n.limits).map(([key,limit])=>{const p=catalog[key],u=used(n,key);return `<div class="provider-row"><div class="provider-label"><span><i class="provider-logo">${icon(key)}</i>${esc(p.name)}</span><b>${limit===null?'Allowed':labelUnit(key,limit)}</b></div>${limit===null?'':`<div class="usage-track"><i style="width:${limit?Math.min(100,u/limit*100):0}%"></i></div><div class="usage-caption"><span>${labelUnit(key,u)} used</span><span>${labelUnit(key,remaining(nodes,n,key))} left</span></div>`}<small class="api-status">${p.service==='OpenAI'?'Demo-capable · no key connected':'No key · catalog only'}${!allowed(nodes,n).includes(key)?' · blocked by parent':''}</small></div>`}).join('')}</div><div class="detail-section"><div class="info-row"><span>Parent</span>${parent?`<button id="selectParent" class="parent-link">${esc(parent.label)}</button>`:'<b>Root</b>'}</div><div class="info-row"><span>Budget period</span><b>${n.period==='session'?'Entire session':'Monthly (UTC)'}</b></div><div class="info-row"><span>Expiry</span><b>${n.until?new Date(n.until).toLocaleString():'No expiry'}</b></div><div class="info-row"><span>Descendants</span><b>${desc(n.id).filter(p=>!p.removed).length}</b></div></div><div class="inherited-note">${icon('shield')} Every parent must allow the API. Expiry and removal cascade. Usage here is simulated.</div>${n.type==='team'?`<button id="addMember" class="detail-button" ${active?'':'disabled'}>Add a member</button>`:''}${parent?`<button id="editLimits" class="detail-button" ${active?'':'disabled'}>Edit permissions</button>`:''}${n.type==='member'?`<button id="startCodex" class="detail-button" ${active?'':'disabled'}>Simulate relay codex</button>`:''}${n.type==='agent'?`<button id="spawnAgents" class="detail-button" ${active?'':'disabled'}>Simulate subagent creation</button>`:''}${session&&Object.hasOwn(n.limits,'codex')?`<button id="useCodex" class="detail-button" ${active?'':'disabled'}>Simulate $0.25 Codex request</button>`:''}${session&&Object.hasOwn(n.limits,'images')?`<button id="useImage" class="detail-button" ${active?'':'disabled'}>Simulate 1 image request</button>`:''}${parent?`<button id="revokeSelected" class="revoke-button" ${n.removed?'disabled':''}>Remove name & descendants</button>`:''}`;
if(parent){$('#selectParent').onclick=()=>select(parent.id);$('#editLimits').onclick=()=>openEditor(n.id);$('#revokeSelected').onclick=openRevoke}if($('#addMember'))$('#addMember').onclick=()=>openEditor(null,n.id);if($('#startCodex'))$('#startCodex').onclick=startCodex;if($('#spawnAgents'))$('#spawnAgents').onclick=spawnAgents;if($('#useCodex'))$('#useCodex').onclick=()=>requestDemo('codex',.25);if($('#useImage'))$('#useImage').onclick=()=>requestDemo('images',1)}
const localDate=t=>{const d=new Date(t);return new Date(t-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function openEditor(id=null,parentId=null){editing=id;const n=id&&get(id);$('#editorTitle').textContent=id?'Edit permissions':'Add a member';const parents=id?[get(n.parent)]:nodes.filter(p=>p.type==='team'&&live(p));$('#parentInput').innerHTML=parents.map(p=>`<option value="${p.id}">${full(p)}</option>`).join('');$('#parentInput').value=n?n.parent:parentId||'dev';$('#nameInput').value=n?n.name:'';$('#nameInput').disabled=!!id;$('#walletInput').value=n?n.wallet:'';$('#walletInput').disabled=!!id;$('#periodInput').value=n?n.period:'month';$('#periodInput').disabled=!!id;$('#untilInput').value=n?.until?localDate(n.until):'';$('#formError').textContent='';updatePermissions();$('#delegateDialog').showModal()}
function updatePermissions(){const p=get($('#parentInput').value),n=editing&&get(editing);$('#permissionInputs').innerHTML=allowed(nodes,p).map(key=>{const c=catalog[key],enabled=n?Object.hasOwn(n.limits,key):['codex','images','github','linear'].includes(key),value=n?.limits[key]??Math.min(p.limits[key]||0,key==='images'?5:20);return `<div class="permission-item"><label><input type="checkbox" data-api="${key}" ${enabled?'checked':''}>${esc(c.name)}</label>${c.unit==='access'?'<span>On / off</span>':`<label class="limit-field"><span>${c.unit==='usd'?'USD':'Count'}</span><input type="number" data-limit="${key}" aria-label="${c.name} limit" min="0" max="${p.limits[key]}" step="${c.unit==='count'?1:.01}" value="${value}" ${enabled?'':'disabled'}></label>`}<small>Parent: ${p.limits[key]===null?'allowed':labelUnit(key,p.limits[key])}</small></div>`}).join('');$$('[data-api]').forEach(el=>el.onchange=()=>{const input=$(`[data-limit="${el.dataset.api}"]`);if(input)input.disabled=!el.checked});$('#parentHint').textContent='Only inherited APIs are listed. Counts and dollar limits are checked independently at every level.'}
$('#parentInput').onchange=updatePermissions;$('#newAccess').onclick=()=>openEditor(null,get(selected).type==='team'?selected:'dev');
$('#delegateForm').onsubmit=e=>{e.preventDefault();try{const p=get($('#parentInput').value),limits=Object.fromEntries($$('[data-api]:checked').map(el=>{const k=el.dataset.api;return [k,catalog[k].unit==='access'?null:Number($(`[data-limit="${k}"]`).value)]})),values={name:$('#nameInput').value.trim(),wallet:$('#walletInput').value.trim(),period:$('#periodInput').value,until:$('#untilInput').value?new Date($('#untilInput').value).getTime():null,limits};let n;if(editing){validate(nodes,p,values,editing);n=get(editing);Object.assign(n,values);log('Demo permissions updated',full(n))}else{n=addIdentity(nodes,p,values);log('Demo member added',full(n)+' · wallet funding not connected')}selected=n.id;branch=chain(nodes,n).find(p=>p.type==='department')?.id||'all';$('#branchSelect').value=branch;render();$('#delegateDialog').close();toast('Saved in demo. No ENS transaction sent.')}catch(error){$('#formError').textContent=error.message}};
function agentWallet(){return '0x'+crypto.randomUUID().replaceAll('-','')+'00000000'}
function startCodex(){try{const p=get(selected),keys=allowed(nodes,p);if(!keys.includes('codex'))throw Error('This member has no Codex permission.');const limits={codex:Math.min(5,p.limits.codex)};if(keys.includes('images'))limits.images=Math.min(2,p.limits.images);const n=addIdentity(nodes,p,{name:'codex',wallet:agentWallet(),limits,period:'session',until:Math.min(Date.now()+8*3600000,p.until||Infinity)});selected=n.id;log('Demo CLI agent created',full(n)+' · simulated relay codex');render()}catch(e){toast(e.message)}}
function spawnAgents(){const p=get(selected);let count=0;for(const [name,key,limit] of [['research','codex',1],['image','images',1]]){if(!allowed(nodes,p).includes(key)||nodes.some(n=>n.parent===p.id&&n.name===name&&!n.removed))continue;try{const n=addIdentity(nodes,p,{name,wallet:agentWallet(),limits:{[key]:Math.min(limit,p.limits[key])},period:'session',until:Math.min(Date.now()+20*60000,p.until||Infinity)});count++;log('Demo subagent created',full(n))}catch(e){toast(e.message)}}render();toast(count?count+' demo subagents created.':'No new eligible subagents to create.')}
function requestDemo(key,amount){const n=get(selected);try{consume(nodes,n,key,amount);log('Simulated request allowed',full(n)+' · '+labelUnit(key,amount)+' · charged to every parent');render();toast('Demo request allowed. No provider was called.')}catch(e){log('Simulated request refused',full(n)+' · '+e.message);toast(e.message)}}
function openRevoke(){const n=get(selected);$('#revokeCopy').textContent=`Remove ${full(n)} and ${desc(n.id).filter(p=>!p.removed).length} descendants? Their access will stop in this demo. Real ENS removal and streaming cutoff require the backend.`;$('#revokeDialog').showModal()}
$('#confirmRevoke').onclick=()=>{const n=get(selected);[n,...desc(n.id)].forEach(p=>p.removed=true);log('Demo branch removed',full(n)+' · all descendants inactive');$('#revokeDialog').close();render();toast('Branch removed. The label can be reused with fresh usage.')};
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function renderActivity(){$('#activityList').innerHTML=events.slice(0,30).map(e=>`<div class="activity-row"><span>${icon('activity')}</span><div><strong>${esc(e.title)}</strong><p>${esc(e.detail)}</p></div><time>${esc(e.time)}</time></div>`).join('')}
function renderProviders(){$('#providerMini').innerHTML=['codex','openai','anthropic','github'].map(key=>`<i class="provider-logo" title="${catalog[key].name}">${icon(key)}</i>`).join('');$('#providerCount').textContent=Object.keys(catalog).length;$('#providerGrid').innerHTML=Object.entries(catalog).map(([key,p])=>`<article class="provider-card"><span class="status-pill">${p.service==='OpenAI'?'Demo-capable · not connected':'No key · catalog only'}</span><h2><span class="provider-logo">${icon(key)}</span>${esc(p.name)}</h2><div class="info-row"><span>Limit type</span><b>${p.unit==='usd'?'Dollar budget':p.unit==='count'?'Image count':'Allowed / denied'}</b></div><p>${p.service==='OpenAI'?'The live demo requires a server-side OpenAI key. This frontend uses simulated requests.':'Can be delegated through the permission editor. Requests need a configured server-side key.'}</p></article>`).join('')}
function showView(view){$$('.view').forEach(el=>el.classList.add('hidden'));$('#'+view+'View').classList.remove('hidden');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#newAccess').innerHTML=icon('plus')+(view==='tree'?' Add a member':' Add a provider');$('#newAccess').onclick=view==='tree'?()=>openEditor(null,get(selected).type==='team'?selected:'dev'):openProvider;const title=view==='tree'?'Access tree':'Providers';$('#pageTitle').innerHTML=title+'<span>.</span>';$('#breadcrumbTitle').textContent=title;if(view==='tree')fitTree()}
$$('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function openProvider(){$('#providerForm').reset();$('#providerError').textContent='';$('#providerDialog').showModal()}
$('#providerForm').onsubmit=e=>{e.preventDefault();const name=$('#providerName').value.trim();if(!name){$('#providerError').textContent='Enter a provider name.';return}if(Object.values(catalog).some(p=>p.name.toLowerCase()===name.toLowerCase())){$('#providerError').textContent='This provider already exists.';return}const key='custom-'+crypto.randomUUID();catalog[key]={name,unit:$('#providerMode').value==='metered'?'usd':'access'};get('acme').limits[key]=catalog[key].unit==='usd'?1000:null;renderProviders();render();log('Demo provider added',name+' · no key configured; no descendant permissions granted');$('#providerDialog').close();toast(name+' added to the catalog. Demo root allowance set; descendants have no access yet.')};
$('#addProvider').textContent='Manage';$('#addProvider').setAttribute('aria-label','Manage provider catalog');$('#addProvider').onclick=()=>showView('providers');
$('#branchSelect').onchange=e=>{branch=e.target.value;render()};
$('#search').oninput=e=>{filter=e.target.value.toLowerCase().trim();render()};
function setZoom(value,fit=false){fitted=fit;zoom=Math.min(1.5,Math.max(.05,value));$('#graph').style.zoom=zoom;$('#zoomValue').textContent=Math.round(zoom*100)+'%';$('#graphScroll').classList.toggle('is-fitted',fit)}
function fitTree(){const b=$('#graphScroll'),g=$('#graph');if(!b.clientWidth)return;setZoom(Math.min(1,(b.clientWidth-24)/parseFloat(g.style.width),(b.clientHeight-24)/parseFloat(g.style.height)),true);b.scrollTo(0,0)}
$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1);$('#fit').onclick=fitTree;
const observer=new ResizeObserver(()=>{if(fitted)fitTree()});observer.observe($('#graphScroll'));
$('#roleSelect').onchange=e=>{const ids={owner:'acme',lead:'eng',team:'dev',member:nodes.find(n=>n.type==='member'&&live(n))?.id,agent:nodes.find(n=>n.type==='agent'&&live(n))?.id};if(!ids[e.target.value]){toast('Create this identity first. Preview roles do not change wallet permissions.');e.target.value='owner';select('acme');return}selected=ids[e.target.value];branch='all';$('#branchSelect').value='all';showView('tree');render();toast('Preview selection only. Actual wallet roles are not connected.')};
$('#reset').onclick=()=>{nodes=seedOrg();selected='dev';branch='all';filter='';$('#branchSelect').value='all';$('#search').value='';events=[];log('Demo reset','Members, agents, sessions and usage cleared; departments and teams retained.');render()};
const onKey=e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('dialog[open]')){e.preventDefault();$('#search').focus()}};document.addEventListener('keydown',onKey);
let previous='';const expiryTimer=setInterval(()=>{const next=nodes.map(n=>status(nodes,n)).join(',');if(previous&&next!==previous)render();previous=next},1000);
renderProviders();render();const frame=requestAnimationFrame(fitTree);
return ()=>{closeProviderList();document.removeEventListener('click',dismissProviders);document.removeEventListener('scroll',closeProviderList,true);document.removeEventListener('keydown',escapeProviders);window.removeEventListener('resize',closeProviderList);observer.disconnect();clearInterval(expiryTimer);clearTimeout(toast.timer);cancelAnimationFrame(frame);document.removeEventListener('keydown',onKey);root.querySelectorAll('*').forEach(el=>{el.onclick=null;el.oninput=null;el.onchange=null;el.onsubmit=null})};
}
