// Generated by scripts/gen-ens-abis.mjs from ensdomains/contracts-v2@71a3b73. Do not edit.

export const CONTRACTS_V2_COMMIT = "71a3b7339dbc55ab47667abdfe8303bac4f4c24e";
export const DEPLOYED_AT = "2026-09-15T09:46:38.513Z";

export const ENSV2_SEPOLIA = {
  BatchRegistrar: {
    address: "0xBe68Ff9aFc7D5A1864ffef5C82DE0A1C13E6B529",
    contractName: "BatchRegistrar",
    sourceName: "src/registrar/BatchRegistrar.sol",
    deployBlock: 11709091n,
  },
  ContractNamer: {
    address: "0xDaB8b3dcb4C2BB181B9215b699b2C3E1fe180ae1",
    contractName: "ContractNamer",
    sourceName: "src/utils/ContractNamer.sol",
    deployBlock: 11708982n,
  },
  DefaultReverseRegistrarAdapter: {
    address: "0x4F32A1c62E202922d4d6307126F43218DB9dA6f5",
    contractName: "DefaultReverseRegistrarAdapter",
    sourceName: "src/reverse-registrar/DefaultReverseRegistrarAdapter.sol",
    deployBlock: 11709078n,
  },
  DNSAliasResolver: {
    address: "0x6FD64A35388D2c22F1Fba96476Db59184B1fEaA0",
    contractName: "DNSAliasResolver",
    sourceName: "src/dns/DNSAliasResolver.sol",
    deployBlock: 11708996n,
  },
  DNSSECGatewayProvider: {
    address: "0x5710eE3945CAA32287553574fE995C0e8e3D613e",
    contractName: "GatewayProvider",
    sourceName: "lib/ens-contracts/contracts/ccipRead/GatewayProvider.sol",
    deployBlock: 11708980n,
  },
  DNSTLDResolver: {
    address: "0xb0C788195697dB17543bF22CBC1b0E2b4A04F9b8",
    contractName: "DNSTLDResolver",
    sourceName: "src/dns/DNSTLDResolver.sol",
    deployBlock: 11708997n,
  },
  DNSTXTResolver: {
    address: "0x1eC6e8D261b1f8Fd0d755eA06186BDc1486197f5",
    contractName: "DNSTXTResolver",
    sourceName: "src/dns/DNSTXTResolver.sol",
    deployBlock: 11708984n,
  },
  ENSV1Resolver: {
    address: "0xb2BF4a9A86d29661EA93223582b9945943931e42",
    contractName: "ENSV1Resolver",
    sourceName: "src/resolver/ENSV1Resolver.sol",
    deployBlock: 11708986n,
  },
  ENSV2Resolver: {
    address: "0x9458eC65b4a703Ee1be03434879F35fd32b64704",
    contractName: "ENSV2Resolver",
    sourceName: "src/resolver/ENSV2Resolver.sol",
    deployBlock: 11708991n,
  },
  ETHRegistrar: {
    address: "0xAbe76F6C8DFcEd81AA5A2bB8034202A7136b94ca",
    contractName: "ETHRegistrar",
    sourceName: "src/registrar/ETHRegistrar.sol",
    deployBlock: 11709083n,
  },
  ETHRegistry: {
    address: "0x657eA849311d3D5823348ddEd7C2AaAFb3EDE09E",
    contractName: "PermissionedRegistry",
    sourceName: "src/registry/PermissionedRegistry.sol",
    deployBlock: 11709066n,
  },
  ETHRenewerV1: {
    address: "0xd06e726e9bD8ac0f33A2a45F4Cc28fe10d656a36",
    contractName: "ETHRenewerV1",
    sourceName: "src/registrar/ETHRenewerV1.sol",
    deployBlock: 11709084n,
  },
  Graveyard: {
    address: "0x950b93885b33cE4C7e8571BE2c88A1aa93D82F49",
    contractName: "Graveyard",
    sourceName: "src/migration/Graveyard.sol",
    deployBlock: 11709080n,
  },
  HCAOwnerAndSessionValidator: {
    address: "0x6A62Af42D4241a02547b096C7DB43ca6411AF813",
    contractName: "HCAOwnerAndSessionValidator",
    sourceName: "src/hca/HCAOwnerAndSessionValidator.sol",
    deployBlock: 11709096n,
  },
  HCAUpgradeSet: {
    address: "0x2ceeDf92Fd032167c90936C9e6cA2931bd7Ec2c0",
    contractName: "PermissionedAddressSet",
    sourceName: "src/utils/PermissionedAddressSet.sol",
    deployBlock: 11709097n,
  },
  LabelStore: {
    address: "0x375C082021E677a40eA2AE094D050602dba90992",
    contractName: "LabelStore",
    sourceName: "src/utils/LabelStore.sol",
    deployBlock: 11708987n,
  },
  LockedMigrationController: {
    address: "0xab1B57C6eE5E91e6090595c0AF14CB9B8bc7773f",
    contractName: "LockedMigrationController",
    sourceName: "src/migration/LockedMigrationController.sol",
    deployBlock: 11709093n,
  },
  ManagedUniversalResolverProxy: {
    address: "0x6d80F2172CFdEc5730fE683860C33d26fC42e6F1",
    contractName: "UpgradableUniversalResolverProxy",
    sourceName: "src/universalResolver/UpgradableUniversalResolverProxy.sol",
    deployBlock: undefined,
  },
  MigrationHelper: {
    address: "0x58d12d60471b98F191856e4C2d56886e9c3eA573",
    contractName: "MigrationHelper",
    sourceName: "src/migration/MigrationHelper.sol",
    deployBlock: 11709095n,
  },
  MockDAI: {
    address: "0x278053aCc97888E63Ec81c80FEC641Bf0Bf19664",
    contractName: "MockERC20",
    sourceName: "test/mocks/MockERC20.sol",
    deployBlock: 11708994n,
  },
  MockUSDC: {
    address: "0x16f95D91DBa7dA3Aca778Ec053dF0FF6C6A8aA8e",
    contractName: "MockERC20",
    sourceName: "test/mocks/MockERC20.sol",
    deployBlock: 11708992n,
  },
  PermissionedResolverImpl: {
    address: "0x14F09Fd05d4585759e54844DC9B00147131Cf243",
    contractName: "PermissionedResolver",
    sourceName: "src/resolver/PermissionedResolver.sol",
    deployBlock: 11709070n,
  },
  PublicResolverSet: {
    address: "0xd12aF6aC82648056Fe7D6B2a9dB97235Aa509021",
    contractName: "PermissionedAddressSet",
    sourceName: "src/utils/PermissionedAddressSet.sol",
    deployBlock: 11709087n,
  },
  PublicResolverV2: {
    address: "0xd7e590Ad0E92A6aC1d81f4483A9B951D3585a50F",
    contractName: "PublicResolverV2",
    sourceName: "src/resolver/PublicResolverV2.sol",
    deployBlock: 11709089n,
  },
  RegistryUpgradeSet: {
    address: "0xd8a8369477b67f837E2B1054b2d47F3D1956b543",
    contractName: "PermissionedAddressSet",
    sourceName: "src/utils/PermissionedAddressSet.sol",
    deployBlock: 11709086n,
  },
  ReverseRegistrarAdapter: {
    address: "0x39993148CAA6a20aE1F08E1b2427966E97f85aaB",
    contractName: "ReverseRegistrarAdapter",
    sourceName: "src/reverse-registrar/ReverseRegistrarAdapter.sol",
    deployBlock: 11709079n,
  },
  RootBatchRegistrar: {
    address: "0xCF5D485A531863856ED9D8A10D61707De7F06c21",
    contractName: "BatchRegistrar",
    sourceName: "src/registrar/BatchRegistrar.sol",
    deployBlock: 11709004n,
  },
  RootRegistry: {
    address: "0x9703DBD26dAB89504490994138cF2c575251a9cE",
    contractName: "PermissionedRegistry",
    sourceName: "src/registry/PermissionedRegistry.sol",
    deployBlock: 11708988n,
  },
  StandaloneHCAFactory: {
    address: "0xB7CFeCEeD32DBa66c507b3c002dAD510b8399928",
    contractName: "StandaloneHCAFactory",
    sourceName: "src/hca/StandaloneHCAFactory.sol",
    deployBlock: 11709077n,
  },
  StandaloneHCAImplementation: {
    address: "0xdF4a24c42921810fed9363b07292E9152578D706",
    contractName: "StandaloneSingleOwnerHCA",
    sourceName: "src/hca/StandaloneSingleOwnerHCA.sol",
    deployBlock: 11709098n,
  },
  StandardRentPriceOracle: {
    address: "0x9B0b9C65BDAf9794Ff7697E4dCFb1f50581072BB",
    contractName: "StandardRentPriceOracle",
    sourceName: "src/registrar/StandardRentPriceOracle.sol",
    deployBlock: 11709073n,
  },
  UniversalHelper: {
    address: "0x33f571aa8A160a21b877cF6E0Fb8806692b97DF5",
    contractName: "UniversalHelper",
    sourceName: "src/universalResolver/UniversalHelper.sol",
    deployBlock: 11709075n,
  },
  UniversalResolverV2: {
    address: "0x5d25C1D6aCBb71B7a28AA7899618a3412a8303e3",
    contractName: "UniversalResolverV2",
    sourceName: "src/universalResolver/UniversalResolverV2.sol",
    deployBlock: 11709101n,
  },
  UnlockedMigrationController: {
    address: "0x7ed171bb143a905F56105e4eA146543Ecb122F55",
    contractName: "UnlockedMigrationController",
    sourceName: "src/migration/UnlockedMigrationController.sol",
    deployBlock: 11709081n,
  },
  UpgradableUniversalResolverProxy: {
    address: "0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe",
    contractName: "UpgradableUniversalResolverProxy",
    sourceName: "src/universalResolver/UpgradableUniversalResolverProxy.sol",
    deployBlock: undefined,
  },
  UserRegistryImpl: {
    address: "0xA80338aAA8D23831cEa25E858D1774534aBb0263",
    contractName: "UserRegistry",
    sourceName: "src/registry/UserRegistry.sol",
    deployBlock: 11709076n,
  },
  VerifiableFactory: {
    address: "0x9e726Eb570beb6BCEb495AB8cdA7df517d4e841C",
    contractName: "VerifiableFactory",
    sourceName: "lib/verifiable-factory/src/VerifiableFactory.sol",
    deployBlock: 11708995n,
  },
  WrapperRegistryImpl: {
    address: "0x2741543c3B14640b97bC70a233318032f7E35bAC",
    contractName: "WrapperRegistry",
    sourceName: "src/registry/WrapperRegistry.sol",
    deployBlock: 11709090n,
  },
} as const;

export type ENSv2ContractName = keyof typeof ENSV2_SEPOLIA;
